# Generated by Django 5.1.1 on 2024-10-25 10:32

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_date_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.user_directory_path, verbose_name='Фотография'),
        ),
    ]
