# Generated by Django 5.1.1 on 2024-11-23 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(verbose_name='дата начала карты')),
                ('mileage', models.PositiveIntegerField(verbose_name='пробег на 1 число месяца')),
                ('remaining_fuel', models.DecimalField(decimal_places=3, max_digits=6, verbose_name='остаток топлива на 1 число месяца')),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='Norm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=20, verbose_name='марка авто и сезон')),
                ('liter_per_km', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='пробег (л/км)')),
                ('work_with_pump_liter_per_min', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='работа с насосом (л/мин)')),
                ('work_without_pump_liter_per_min', models.DecimalField(decimal_places=3, max_digits=4, verbose_name='работа без насоса (л/мин)')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='марка автомобиля')),
                ('full_name', models.CharField(max_length=30, verbose_name='полное название автомобиля')),
                ('number', models.CharField(max_length=20, verbose_name='номер автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='дата выезда')),
                ('departure_time', models.TimeField(verbose_name='время выезда')),
                ('return_time', models.TimeField(verbose_name='время возвращения')),
                ('place_of_work', models.CharField(max_length=40, verbose_name='место/цель выезда')),
                ('distance', models.PositiveIntegerField(blank=True, null=True, verbose_name='пройдено (км)')),
                ('mileage_end', models.PositiveIntegerField(blank=True, null=True, verbose_name='пробег после выезда (км)')),
                ('with_pump', models.PositiveIntegerField(blank=True, null=True, verbose_name='с насосом (мин)')),
                ('without_pump', models.PositiveIntegerField(blank=True, null=True, verbose_name='без насоса (мин)')),
                ('refueled', models.PositiveIntegerField(blank=True, null=True, verbose_name='заправлено (л)')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='cards.card', verbose_name='карточка')),
            ],
            options={
                'ordering': ['-date', '-return_time'],
            },
        ),
    ]
