# Generated by Django 5.1.1 on 2024-11-26 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='departure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
        ),
        migrations.AddField(
            model_name='departure',
            name='norm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='cards.norm', verbose_name='норма'),
        ),
        migrations.AddField(
            model_name='card',
            name='norm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.norm', verbose_name='норма расхода топлива'),
        ),
        migrations.AddField(
            model_name='card',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='cards.truck', verbose_name='автомобиль'),
        ),
    ]
