# Generated by Django 5.1.1 on 2024-11-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departure',
            name='mileage_end',
        ),
    ]
