# Generated by Django 5.1.1 on 2024-11-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_remove_departure_mileage_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='departure',
            name='departure_datetime',
            field=models.DateTimeField(default='2024-1-1 12:01:01', verbose_name='время и дата выезда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departure',
            name='return_time_datetime',
            field=models.DateTimeField(default='2024-1-1 12:01:01', verbose_name='время и дата возвращения'),
            preserve_default=False,
        ),
    ]
