# Generated by Django 5.1.1 on 2024-11-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_departure_departure_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departure',
            old_name='return_time_datetime',
            new_name='return_datetime',
        ),
    ]
