# Generated by Django 5.1.1 on 2024-11-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_remove_departure_departure_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departure',
            name='departure_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время и дата выезда'),
        ),
        migrations.AddField(
            model_name='departure',
            name='return_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='время и дата возвращения'),
        ),
    ]
